PizzaWebApp/Models/ErrorViewModel.cs
using System;

namespace ClassLibrary
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PizzaWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ClassLibrary;

namespace PizzaWebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PizzaWebApp/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PizzaWebApp.Models;
using PizzaWebApp.Repositories;
using ClassLibrary;

namespace PizzaWebApp.Controllers
{
    public class OrderController : Controller
    {

        public IStoreRepo Repo { get; set; }

        public OrderController(IStoreRepo repo)
        {
            Repo = repo;
        }


        // GET: Order
        public ActionResult Index()
        {
            return View();
        }

        // GET: Order/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Order/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Order/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrderClass order)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Repo.MakeOrder(order);
                }

                else
                {
                    return View();
                }

                return RedirectToAction(nameof(Index));

            }
            catch(ArgumentException ex)
            {
                return View();
            }
        }

        // GET: Order/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Order/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Order/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Order/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

PizzaWebApp/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ClassLibrary;
using DataAccess;
using PizzaWebApp.Repositories;

namespace PizzaWebApp.Controllers
{
    public class StoreController : Controller
    {
        public IStoreRepo Repo { get; set; }

        public StoreController(IStoreRepo repo)
        {
            Repo = repo;
        }

        // GET: Store
        public ActionResult Index()
        {
            return View(Repo.GetStores());
        }

        public ActionResult StoresRestocked(int id)
        {
            Repo.RestockStore(id);
            return View();
        }

        public ActionResult StoreOrders(int id)
        {           
            return View(Repo.StoreOrders(id));
        }

        // GET: Store/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Store/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Store/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Store/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Store/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Store/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Store/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

PizzaWebApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PizzaWebApp.Repositories;
using ClassLibrary;
using DataAccess;

namespace PizzaWebApp.Controllers
{
    public class UserController : Controller
    {

        public IStoreRepo Repo { get; set; }


        public UserController(IStoreRepo repo)
        {
            Repo = repo;
        }

        // GET: User
        public ActionResult Index()
        {
            return View(Repo.GetUsers());
        }

        // GET: User/Details/5
        public ActionResult UserOrderHistory(int id)
        {
            //orderHistory = ;
            return View(Repo.UserOrders(id));
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: User/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

PizzaWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Generic's Pizza</h1>
</div>

PizzaWebApp/Views/Order/Create.cshtml
@model ClassLibrary.OrderClass

@{
    ViewData["Title"] = "Create";
}

<div class="text-center">
    <h1>Place your order here.</h1>
</div>

<div>
    <p>
        <ul>
            <li>Small Pizza: $25</li>
            <li>Large Pizza: $50</li>
        </ul>
    </p>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="user" class="control-label">User ID</label>
                <input asp-for="user" class="form-control" />
                <span asp-validation-for="user" class="text-danger"></span>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <select asp-for="locationName">
                    <option value="Pizza Store A">Pizza Store A</option>
                    <option value="Pizza Store B">Pizza Store B</option>
                    <option value="Pizza Store C">Pizza Store C</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="smallPizzas" class="control-label">Small Pizzas</label>
                <input asp-for="smallPizzas" class="form-control" />
                <span asp-validation-for="smallPizzas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="largePizzas" class="control-label">Large Pizzas</label>
                <input asp-for="largePizzas" class="form-control" />
                <span asp-validation-for="largePizzas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PizzaWebApp/Views/Order/Details.cshtml
@model IEnumerable<DataAccess.OrderDetails>

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrderId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LocationID)
            </th>
            <th>
                Store
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserID)
            </th>
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
            <th>
                @Html.DisplayNameFor(model => model.smallPizzas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.largePizzas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DatePlaced)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrderId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LocationID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.locationName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.firstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.smallPizzas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.largePizzas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatePlaced)
            </td>

        </tr>
}
    </tbody>
</table>

PizzaWebApp/Views/Order/OrderCompleted.cshtml
@{
    ViewData["Title"] = "OrderCompleted";
}

<div class="text-center">
    <h1>Order Completed Successfully!</h1>
</div>

PizzaWebApp/Views/Order/OrderFailed.cshtml
@{
    ViewData["Title"] = "OrderFailed";
}

<h3><font color="red">Order failed. You may have ordered too recently, made your order too large, or the shop you have chosen may be out of stock.</font></h3>

PizzaWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PizzaWebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PizzaWebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Create">Make Order</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Index">Stores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2018 - PizzaWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

PizzaWebApp/Views/Store/Index.cshtml
@model IEnumerable<DataAccess.Store>

@{
    ViewData["Title"] = "Index";
}
<head>
    <style>
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>

<div class="text-center">
    <h1>List of Store Locations</h1>
</div>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table" border="1">
    <thead>
        <tr>
            <th>
                Location ID
            </th>
            <th>
                Store Name
            </th>
            <th>
                Inventory
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LocationId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LocationName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stock)
                </td>
                <td>
                    @Html.ActionLink("Restock", "StoresRestocked", new { id = item.LocationId }) |
                    @Html.ActionLink("Order History", "StoreOrders", new { id = item.LocationId })
                </td>
            </tr>
        }
    </tbody>
</table>

PizzaWebApp/Views/Store/StoreOrders.cshtml
@model IEnumerable<DataAccess.OrderDetails>

@{
    ViewData["Title"] = "StoreOrders";
}

<head>
    <style>
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>

<div class="text-center">
    <h1>Store Order History</h1>
</div>

<table class="table" border="1">
    <thead>
        <tr>
            <th>
                Order ID
            </th>
            <th>
                User ID
            </th>
            <th>
                Store
            </th>
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
            <th>
                Small Pizzas
            </th>
            <th>
                Large Pizzas
            </th>
            <th>
                Price
            </th>
            <th>
                Date
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrderId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.locationName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.firstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.smallPizzas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.largePizzas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatePlaced)
            </td>
        </tr>
}
    </tbody>
</table>

PizzaWebApp/Views/Store/StoresRestocked.cshtml
@{
    ViewData["Title"] = "StoresRestocked";
}

<h3>Store has been restocked!</h3>

PizzaWebApp/Views/User/Details.cshtml
@model IEnumerable<ClassLibrary.UserClass>

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                User ID
            </th>
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
            <th>
                Default Location
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.userID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.firstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.defaultLocation)
            </td>
            <td>               
                @Html.ActionLink("Order History", "UserOrderDetails", new { id = item.userID })                
            </td>
        </tr>
}
    </tbody>
</table>

PizzaWebApp/Views/User/Index.cshtml
@model IEnumerable<ClassLibrary.UserClass>

@{
    ViewData["Title"] = "Index";
}

<head>
    <style>
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>

<div class="text-center">
    <h1>List of Users</h1>
</div>


<table class="table" border="1">
    <thead>
        <tr>
            <th>
                User ID
            </th>
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
            <th>
                Default Location
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.userID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.firstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.defaultLocation)
            </td>
            <td>
                @Html.ActionLink("Order History", "UserOrderHistory", new { id = item.userID })
            </td>
        </tr>
}
    </tbody>
</table>

PizzaWebApp/Views/User/UserOrderHistory.cshtml
@model IEnumerable<DataAccess.OrderDetails>

@{
    ViewData["Title"] = "UserOrderHistory";
}

<head>
    <style>
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>

<div class="text-center">
    <h1>User Order History</h1>
</div>

<table class="table" border="1">
    <thead>
        <tr>
            <th>
                Order ID
            </th>
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
            <th>
                Store
            </th>
            <th>
                Small Pizzas
            </th>
            <th>
                Large Pizzas
            </th>
            <th>
                Price
            </th>
            <th>
                Date
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrderId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.firstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.locationName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.smallPizzas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.largePizzas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatePlaced)
            </td>

        </tr>
}
    </tbody>
</table>